matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.4
      script:
      - cd backend
      - dotnet restore
      - dotnet test ChequeIN.Tests
    - language: node_js
      node_js: "8"
      before_install:
        - cd frontend

